framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            sms_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: sms_notification_failure
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                        name: notifications
                    queues:
                        sms_notification: ~

            sms_notification_failure:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILURE)%'
                options:
                    exchange:
                        name: notifications
                    queues:
                        sms_notification_failure: ~

        routing:
            # Route your messages to the transports
            'App\Messages\SmsNotification': sms_notification

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
